"""initial migration

Revision ID: 611554e60d4f
Revises: 
Create Date: 2023-11-10 11:02:44.857316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611554e60d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=6), nullable=False),
    sa.Column('long_url', sa.String(length=255), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
